### ISSUE TITLE
感觉action时间不太够用啊？

### ISSUE THREAD

**Issue by ljh740** [sgzman/my_action_jd_scripts#2]
免费额度一个月2000分钟？
大佬怎么解决的？还是pay了？
pay费用多少？

**Comment by sgzman** [comment]
既然是白嫖，pay就是肯定不值得了。想想别的办法吧

**Comment by ljh740** [comment]
> 既然是白嫖，pay就是肯定不值得了。想想别的办法吧

多账号？算了我还是直接扔docker里
