### ISSUE TITLE
红包雨时间问题

### ISSUE THREAD

**Issue by longwangv1w2** [sgzman/my_action_jd_scripts#4]
老哥，你这红包雨的corn设置后能拿到奖励吗？ac有延迟吧

**Comment by sgzman** [comment]
> 老哥，你这红包雨的corn设置后能拿到奖励吗？ac有延迟吧

没办法呀。我还没搞别的运行方式。目前只有这个了。

**Comment by longwangv1w2** [comment]
> > 老哥，你这红包雨的corn设置后能拿到奖励吗？ac有延迟吧
> 
> 没办法呀。我还没搞别的运行方式。目前只有这个了。

是啊 放弃了
